import type { LogSeverity } from '../shared/types'

const DEFAULT_SESSION_LIMIT = 50
const DEFAULT_REFILL_PER_MINUTE = 1
const DEFAULT_ERROR_RESERVE = 0.2
const DEFAULT_DUPLICATE_LIMIT = 3
const DEFAULT_STORAGE_KEY = 'fsl_ratelimit'
const DEFAULT_SUMMARY_INTERVAL_MINUTES = 60
const DEFAULT_SUMMARY_MAX_AGE_DAYS = 7
const DEFAULT_MAX_PENDING_SUMMARIES = 50

// Fixed, not configurable — the seven knobs in RateLimitConfig are the whole
// documented surface (README, "Volume controls"). A second storage key for the
// summary queue would be an eighth nobody asked for.
const SUMMARY_STORAGE_KEY = 'fsl_pending_summaries'

export interface RateLimitConfig {
  /** The budget: how many logs can go out at once. Default 50. */
  sessionLimit?: number
  /** How fast the budget comes back, per minute. Default 1. */
  refillPerMinute?: number
  /** Share of `sessionLimit` only ERROR and above may spend. Default 0.2. */
  errorReserve?: number
  /** Full copies of one error before it is only counted. Default 3. */
  duplicateLimit?: number
  storageKey?: string
  /** How often a running count of repeats is sent as a summary. Default 60. */
  summaryIntervalMinutes?: number
  /** How long an unsent summary is kept before it is deleted, not sent. Default 7. */
  summaryMaxAgeDays?: number
  /** Most pending summaries kept at once; oldest are dropped first. Default 50. */
  maxPendingSummaries?: number
}

/**
 * The state a single signature accumulates: how many full copies have gone
 * out (capped at `duplicateLimit`), the client-side id those copies carry as
 * `labels.repeatKey` (see the module doc below), and — once the limit is
 * passed — a running count of repeats waiting to become a summary.
 */
interface SignatureState {
  count: number
  repeatKey: string
  repeatCount?: number
  firstSeen?: number
  lastSeen?: number
  labels?: Record<string, string | undefined>
  message?: string
}

interface RateLimitState {
  available: number
  lastRefillAt: number
  signatures: Record<string, SignatureState>
}

/**
 * A repeat count waiting to be sent as a WARNING summary. Queued in
 * `localStorage` so it survives the tab closing — `sessionStorage` does not.
 *
 * `bootId` is what `sentLate` is built from: it is the module's own load-time
 * id, not anything persisted. A summary queued during an earlier page load
 * carries a different `bootId` than the one currently running, so popping it
 * here reveals it as "from a previous visit" without needing a server
 * round-trip or a wall-clock guess.
 */
export interface PendingSummary {
  id: string
  message: string
  labels: Record<string, string | undefined>
  repeatOf: string
  repeatCount: number
  firstSeen: string
  lastSeen: string
  createdAt: number
  bootId: string
}

export interface SentSummary {
  message: string
  labels: Record<string, string | undefined>
  repeatOf: string
  repeatCount: number
  firstSeen: string
  lastSeen: string
  sentLate: boolean
}

// Session-scoped by design: one browser session, one budget. Deliberately not
// per-Logger — see the module-scoped state rule in CLAUDE.md.
let config: Required<RateLimitConfig> = {
  sessionLimit: DEFAULT_SESSION_LIMIT,
  refillPerMinute: DEFAULT_REFILL_PER_MINUTE,
  errorReserve: DEFAULT_ERROR_RESERVE,
  duplicateLimit: DEFAULT_DUPLICATE_LIMIT,
  storageKey: DEFAULT_STORAGE_KEY,
  summaryIntervalMinutes: DEFAULT_SUMMARY_INTERVAL_MINUTES,
  summaryMaxAgeDays: DEFAULT_SUMMARY_MAX_AGE_DAYS,
  maxPendingSummaries: DEFAULT_MAX_PENDING_SUMMARIES,
}

export function configureRateLimiter(options: RateLimitConfig): void {
  config = { ...config, ...options }
}

// This tab's identity for `sentLate`. Regenerated by `resetRateLimiter`, which
// is how tests simulate a new visit — a real reload gets a new one for free,
// since the module (and this `let`) is re-evaluated from scratch.
let bootId = generateId()

function generateId(): string {
  return `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 10)}`
}

function defaultState(): RateLimitState {
  return { available: config.sessionLimit, lastRefillAt: Date.now(), signatures: {} }
}

function readState(): RateLimitState {
  try {
    const stored = sessionStorage.getItem(config.storageKey)
    return stored ? (JSON.parse(stored) as RateLimitState) : defaultState()
  } catch {
    return defaultState()
  }
}

function writeState(state: RateLimitState): void {
  try {
    sessionStorage.setItem(config.storageKey, JSON.stringify(state))
  } catch {
    // sessionStorage full or unavailable — rate limiting degrades, logging continues
  }
}

function readSummaryQueue(): PendingSummary[] {
  try {
    const stored = localStorage.getItem(SUMMARY_STORAGE_KEY)
    return stored ? (JSON.parse(stored) as PendingSummary[]) : []
  } catch {
    return []
  }
}

function writeSummaryQueue(queue: PendingSummary[]): void {
  try {
    localStorage.setItem(SUMMARY_STORAGE_KEY, JSON.stringify(queue))
  } catch {
    // localStorage full or unavailable — summaries degrade, logging continues
  }
}

function isExpired(summary: PendingSummary, now: number): boolean {
  return now - summary.createdAt >= config.summaryMaxAgeDays * 24 * 60 * 60 * 1000
}

/**
 * Refill the budget for the time elapsed since it was last touched, capped at
 * `sessionLimit`. Mutates `state` in place; the caller decides whether the
 * result is worth persisting.
 */
function refill(state: RateLimitState, now: number): void {
  const elapsedMinutes = (now - state.lastRefillAt) / 60_000
  if (elapsedMinutes <= 0) return
  state.available = Math.min(config.sessionLimit, state.available + elapsedMinutes * config.refillPerMinute)
  state.lastRefillAt = now
}

/**
 * Build the key used to recognise a repeat of the same problem. Two occurrences
 * count as duplicates only if the message and the screen both match, so the same
 * error from two different screens is not collapsed into one.
 *
 * This is coarse: the same error reached by two different paths on ONE screen
 * still collapses, and the second path can be suppressed before anyone sees it.
 * See #29 — deriving the path from breadcrumbs would discriminate properly,
 * without the staleness of a span someone has to remember to clear.
 */
export function signatureFor(
  error: Error | string,
  screen?: string,
): string {
  const str = error instanceof Error ? `${error.name}:${error.message}` : String(error)
  return `${str}|${screen ?? ''}`
}

/**
 * A signature is further scoped to the release and the user before it is
 * counted — two releases, or two people on one machine, must never share one
 * running count. See README, "Repeats are counted, not dropped".
 */
function compoundKey(signature: string, labels: Record<string, string | undefined> | undefined): string {
  return `${signature}|${labels?.releaseId ?? ''}|${labels?.userId ?? ''}`
}

export type RateLimitDecision =
  | { allowed: true; repeatKey?: string }
  | { allowed: false; reason: 'session-limit' | 'reserve' | 'duplicate'; signature?: string }

export interface AllowOptions {
  signature?: string
  severity: LogSeverity
  message?: string
  labels?: Record<string, string | undefined>
}

/**
 * Decide whether one log may be sent, and consume its budget if so.
 *
 * Check and consume are one operation on purpose. They used to be separate
 * exports called from two different layers, which meant an error was checked
 * against the session limit twice and counted against it twice — a configured
 * limit of 50 was really 25 for errors. A single call cannot double-count, and
 * cannot be checked without consuming.
 *
 * Pass a `signature` to opt this log into duplicate suppression. Any severity
 * may do so; it is not reserved for errors. Once `duplicateLimit` full copies
 * have gone out, further occurrences are neither sent nor refused outright —
 * they are counted here, toward the next repeat summary, and cost no budget.
 */
export function allow(options: AllowOptions): RateLimitDecision {
  const now = Date.now()
  const state = readState()
  refill(state, now)

  let key: string | undefined
  let sig: SignatureState | undefined
  if (options.signature !== undefined) {
    key = compoundKey(options.signature, options.labels)
    sig = state.signatures[key] ?? { count: 0, repeatKey: generateId() }
  }

  if (sig && key && sig.count >= config.duplicateLimit) {
    sig.repeatCount = (sig.repeatCount ?? 0) + 1
    if (sig.firstSeen === undefined) sig.firstSeen = now
    sig.lastSeen = now
    if (sig.labels === undefined) sig.labels = options.labels
    if (sig.message === undefined) sig.message = options.message
    state.signatures[key] = sig
    writeState(state)
    return { allowed: false, reason: 'duplicate', signature: options.signature }
  }

  const reserveThreshold = config.sessionLimit * config.errorReserve
  if (state.available < 1) {
    writeState(state)
    return { allowed: false, reason: 'session-limit' }
  }
  if (state.available <= reserveThreshold && options.severity !== 'ERROR') {
    writeState(state)
    return { allowed: false, reason: 'reserve' }
  }

  state.available -= 1
  if (sig && key) {
    sig.count += 1
    state.signatures[key] = sig
  }
  writeState(state)
  return { allowed: true, repeatKey: sig?.repeatKey }
}

/**
 * Move any signature's accumulated repeats into the pending-summary queue —
 * every one whose window (`summaryIntervalMinutes`) has elapsed, or every one
 * with anything to send when `force` is true (the tab going hidden).
 *
 * Only the counting resets; `count` (full copies already sent) is untouched,
 * so a signature stays in "counting" mode across summary windows rather than
 * sending three more full copies before the next summary.
 */
export function flushDueSummaries(force = false): void {
  const now = Date.now()
  const state = readState()
  refill(state, now)
  const intervalMs = config.summaryIntervalMinutes * 60_000

  let changed = false
  for (const key of Object.keys(state.signatures)) {
    const sig = state.signatures[key]
    if (!sig.repeatCount || sig.firstSeen === undefined || sig.lastSeen === undefined) continue
    if (!force && now - sig.firstSeen < intervalMs) continue

    const maxAgeMs = config.summaryMaxAgeDays * 24 * 60 * 60 * 1000
    const queue = readSummaryQueue().filter((s) => now - s.createdAt < maxAgeMs)
    queue.push({
      id: generateId(),
      message: sig.message ?? '',
      labels: sig.labels ?? {},
      repeatOf: sig.repeatKey,
      repeatCount: sig.repeatCount,
      firstSeen: new Date(sig.firstSeen).toISOString(),
      lastSeen: new Date(sig.lastSeen).toISOString(),
      createdAt: now,
      bootId,
    })
    // Keep the newest when the queue is over its cap.
    const trimmed = queue.length > config.maxPendingSummaries
      ? queue.slice(queue.length - config.maxPendingSummaries)
      : queue
    writeSummaryQueue(trimmed)

    sig.repeatCount = undefined
    sig.firstSeen = undefined
    sig.lastSeen = undefined
    sig.labels = undefined
    sig.message = undefined
    changed = true
  }

  if (changed) writeState(state)
}

/**
 * Claim every pending summary not past `summaryMaxAgeDays`, and empty the
 * queue — this tab now owns sending them. `sentLate` is true for anything
 * queued by an earlier page load (a different `bootId`): the case the
 * README's "next visit sends them" describes.
 */
export function takePendingSummaries(): SentSummary[] {
  const now = Date.now()
  const queue = readSummaryQueue()
  const fresh = queue.filter((s) => !isExpired(s, now))
  writeSummaryQueue([])
  return fresh.map((s) => ({
    message: s.message,
    labels: s.labels,
    repeatOf: s.repeatOf,
    repeatCount: s.repeatCount,
    firstSeen: s.firstSeen,
    lastSeen: s.lastSeen,
    sentLate: s.bootId !== bootId,
  }))
}

/**
 * Test-only reset. There is no `beforeunload` wiring any more — the budget
 * lives in `sessionStorage` on purpose, so a reload keeps it — but tests still
 * need a way to start a clean session, and to simulate a genuinely new visit
 * (a new tab gets a new `bootId` for free, since the module reloads with it;
 * a test in the same process cannot, so this rotates it explicitly).
 */
export function resetRateLimiter(): void {
  try {
    sessionStorage.removeItem(config.storageKey)
  } catch {
    // Silently fail
  }
  bootId = generateId()
}
